aws_region                  = "us-east-1"
vpc_cidr                    = "10.0.0.0/16"
vpc_name                    = "dev_jay_VPC"
environment                 = "Development"
key_name                    = "us"
instance_type               = "t2.micro"
public_subnets_cidr_blocks  = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
private_subnets_cidr_blocks = ["10.0.0.4/24", "10.0.0.5/24", "10.0.0.6/24"]
azs                         = ["us-east-1a", "us-east-1b", "us-east-1c"]
nlb_name                    = "dev-NLB"
TG_name                     = "dev-TG"
